# Generated by Django 4.0.3 on 2022-03-29 14:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255,
                                           verbose_name='title')),
                ('description', models.TextField(
                    blank=True,
                    verbose_name='description',
                    null=True
                    )),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField(blank=True, validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10)],
                    verbose_name='rating', null=True)),
                ('type', models.CharField(choices=[
                    ('movie', 'Movie'),
                    ('tv_show', 'Tv Show')],
                    default='movie', max_length=7, verbose_name='type')),
            ],
            options={
                'verbose_name': 'filmwork',
                'verbose_name_plural': 'filmworks',
                'db_table': 'content"."film_work',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255,
                                          verbose_name='name')),
                ('description', models.TextField(blank=True,
                                                 verbose_name='description')),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'db_table': 'content"."genre',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('full_name', models.TextField(verbose_name='full_name')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'content"."person',
            },
        ),
        migrations.CreateModel(
            name='PersonFilmwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False)),
                ('role', models.TextField(null=True, verbose_name='role')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('film_work', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='movies.filmwork',
                    )),
                ('person', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='movies.person'
                    )),
            ],
            options={
                'db_table': 'content"."person_film_work',
            },
        ),
        migrations.CreateModel(
            name='GenreFilmwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('film_work', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='movies.filmwork',
                    verbose_name='Filmwork'
                    )),
                ('genre', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='movies.genre',
                    verbose_name='Genre')),
            ],
            options={
                'db_table': 'content"."genre_film_work',
            },
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(
                fields=['creation_date', 'rating'],
                name='fw_creation_date_rating_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['rating'], name='fw_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['title'], name='fw_title_idx'),
        ),
        migrations.AddIndex(
            model_name='personfilmwork',
            index=models.Index(
                fields=['film_work_id', 'person_id'],
                name='film_work_person_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='genrefilmwork',
            constraint=models.UniqueConstraint(
                fields=('film_work_id', 'genre_id'),
                name='genre_film_work_film_work_id_genre_id_uniq'
            ),
        ),
    ]
