# Generated by Django 4.0.3 on 2022-04-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_genrefilmwork_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(
                choices=[
                    ('актер', 'Actor'),
                    ('режиссер', 'Director'),
                    ('сценарист', 'Screenwriter'),
                    ('художник по костюмам', 'Costumedesigner'),
                    ('композитор', 'Composer')
                ],
                null=True, verbose_name='role'),
        ),
    ]
